name: aestro_vista
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  # Icons
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  youtube_player_flutter: ^9.1.0
  url_launcher: ^6.3.2

  # Networking
  dio: ^5.7.0

  # State & DI
  get_it: ^8.0.0
  equatable: ^2.0.7

  # Storage
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true